#!/usr/bin/env python3
"""
StatViz Demo Report Generator
=============================
Generates the HTML report and DOCX document for the demo page.
Uses the fake research dataset generated by generate_demo_data.py.

Research Topic: הקשר בין שימוש ברשתות חברתיות לבין דימוי גוף ודיכאון בקרב מתבגרים
"""

import pandas as pd
import numpy as np
from scipy import stats
import json
import base64
from io import BytesIO

# Try to import docx for Word document generation
try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False
    print("Warning: python-docx not installed, DOCX generation skipped")

# Try to import plotting libraries
try:
    import plotly.graph_objects as go
    import plotly.express as px
    from plotly.subplots import make_subplots
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False
    print("Warning: Plotly not installed, will use basic charts")

def load_data():
    """Load the generated demo dataset."""
    df = pd.read_excel('demo_dataset.xlsx')
    return df

def calculate_cronbach_alpha(items_df):
    """Calculate Cronbach's alpha for reliability."""
    items = items_df.values
    n_items = items.shape[1]
    item_vars = items.var(axis=0, ddof=1)
    total_var = items.sum(axis=1).var(ddof=1)
    alpha = (n_items / (n_items - 1)) * (1 - item_vars.sum() / total_var)
    return alpha

def generate_plotly_chart(fig, chart_id):
    """Convert Plotly figure to embeddable HTML."""
    return fig.to_html(full_html=False, include_plotlyjs=False, div_id=chart_id)

def create_correlation_heatmap(df):
    """Create correlation heatmap for main variables."""
    corr_vars = ['ממוצע_רשתות', 'ממוצע_דימוי_גוף', 'ממוצע_דיכאון']
    corr_labels = ['שימוש ברשתות', 'דימוי גוף', 'דיכאון']
    corr_matrix = df[corr_vars].corr()

    # Convert to lists to avoid binary encoding issues in HTML export
    z_data = corr_matrix.values.tolist()
    text_data = np.round(corr_matrix.values, 3).tolist()

    fig = go.Figure(data=go.Heatmap(
        z=z_data,
        x=corr_labels,
        y=corr_labels,
        colorscale='RdBu_r',
        zmid=0,
        text=text_data,
        texttemplate='%{text}',
        textfont={"size": 14},
        hovertemplate='%{x} ↔ %{y}<br>r = %{z:.3f}<extra></extra>'
    ))

    fig.update_layout(
        title=dict(text='מטריצת קורלציות', font=dict(size=18)),
        height=400,
        font=dict(family='Rubik, sans-serif'),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )

    return fig

def create_gender_comparison_chart(df):
    """Create bar chart comparing body image by gender."""
    gender_means = df.groupby('מגדר')['ממוצע_דימוי_גוף'].agg(['mean', 'std', 'count'])
    gender_means['se'] = gender_means['std'] / np.sqrt(gender_means['count'])

    fig = go.Figure()

    colors = {'בן': '#3B82F6', 'בת': '#EC4899'}

    for gender in ['בן', 'בת']:
        fig.add_trace(go.Bar(
            name=gender,
            x=[gender],
            y=[gender_means.loc[gender, 'mean']],
            error_y=dict(type='data', array=[gender_means.loc[gender, 'se'] * 1.96]),
            marker_color=colors[gender],
            text=[f'{gender_means.loc[gender, "mean"]:.2f}'],
            textposition='outside'
        ))

    fig.update_layout(
        title=dict(text='דימוי גוף לפי מגדר', font=dict(size=18)),
        yaxis_title='ממוצע דימוי גוף',
        showlegend=False,
        height=400,
        font=dict(family='Rubik, sans-serif'),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )

    return fig

def create_sector_comparison_chart(df):
    """Create bar chart comparing social media use by sector."""
    sector_order = ['ממלכתי', 'ממ"ד', 'חרדי']
    sector_means = df.groupby('סוג_בית_ספר')['ממוצע_רשתות'].agg(['mean', 'std', 'count'])
    sector_means['se'] = sector_means['std'] / np.sqrt(sector_means['count'])

    fig = go.Figure()

    colors = ['#3B82F6', '#8B5CF6', '#06B6D4']

    for i, sector in enumerate(sector_order):
        if sector in sector_means.index:
            fig.add_trace(go.Bar(
                name=sector,
                x=[sector],
                y=[sector_means.loc[sector, 'mean']],
                error_y=dict(type='data', array=[sector_means.loc[sector, 'se'] * 1.96]),
                marker_color=colors[i],
                text=[f'{sector_means.loc[sector, "mean"]:.2f}'],
                textposition='outside'
            ))

    fig.update_layout(
        title=dict(text='שימוש ברשתות חברתיות לפי סוג בית ספר', font=dict(size=18)),
        yaxis_title='ממוצע שימוש ברשתות',
        showlegend=False,
        height=400,
        font=dict(family='Rubik, sans-serif'),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )

    return fig

def create_scatter_plot(df, x_col, y_col, x_label, y_label, title):
    """Create scatter plot with regression line."""
    fig = go.Figure()

    # Convert to lists to avoid binary encoding issues in HTML export
    x_data = df[x_col].tolist()
    y_data = df[y_col].tolist()

    # Add scatter points
    fig.add_trace(go.Scatter(
        x=x_data,
        y=y_data,
        mode='markers',
        marker=dict(
            color='#6366F1',
            size=8,
            opacity=0.6
        ),
        name='נבדקים'
    ))

    # Add regression line
    slope, intercept, r_value, p_value, std_err = stats.linregress(df[x_col], df[y_col])
    x_min, x_max = float(df[x_col].min()), float(df[x_col].max())
    x_line = [x_min, x_max]
    y_line = [slope * x_min + intercept, slope * x_max + intercept]

    fig.add_trace(go.Scatter(
        x=x_line,
        y=y_line,
        mode='lines',
        line=dict(color='#EF4444', width=2, dash='dash'),
        name=f'קו רגרסיה (r={r_value:.2f})'
    ))

    fig.update_layout(
        title=dict(text=title, font=dict(size=18)),
        xaxis_title=x_label,
        yaxis_title=y_label,
        height=400,
        font=dict(family='Rubik, sans-serif'),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
    )

    return fig

def create_mediation_diagram():
    """Create mediation path diagram."""
    fig = go.Figure()

    # Boxes for variables
    boxes = [
        {'x': 0.1, 'y': 0.5, 'text': 'שימוש ברשתות<br>חברתיות', 'color': '#3B82F6'},
        {'x': 0.5, 'y': 0.85, 'text': 'דימוי גוף', 'color': '#8B5CF6'},
        {'x': 0.9, 'y': 0.5, 'text': 'דיכאון', 'color': '#EF4444'},
    ]

    for box in boxes:
        fig.add_shape(
            type='rect',
            x0=box['x']-0.12, y0=box['y']-0.12,
            x1=box['x']+0.12, y1=box['y']+0.12,
            fillcolor=box['color'],
            line=dict(color=box['color'], width=2),
            opacity=0.8
        )
        fig.add_annotation(
            x=box['x'], y=box['y'],
            text=box['text'],
            showarrow=False,
            font=dict(color='white', size=12, family='Rubik'),
        )

    # Arrows with coefficients
    arrows = [
        {'x0': 0.22, 'y0': 0.55, 'x1': 0.38, 'y1': 0.75, 'text': 'a = -0.40***', 'tx': 0.25, 'ty': 0.7},
        {'x0': 0.62, 'y0': 0.75, 'x1': 0.78, 'y1': 0.55, 'text': 'b = -0.35***', 'tx': 0.75, 'ty': 0.7},
        {'x0': 0.22, 'y0': 0.5, 'x1': 0.78, 'y1': 0.5, 'text': "c' = 0.20*", 'tx': 0.5, 'ty': 0.35},
    ]

    for arrow in arrows:
        fig.add_annotation(
            x=arrow['x1'], y=arrow['y1'],
            ax=arrow['x0'], ay=arrow['y0'],
            xref='x', yref='y', axref='x', ayref='y',
            showarrow=True,
            arrowhead=2,
            arrowsize=1.5,
            arrowwidth=2,
            arrowcolor='#374151'
        )
        fig.add_annotation(
            x=arrow['tx'], y=arrow['ty'],
            text=arrow['text'],
            showarrow=False,
            font=dict(size=11, color='#374151', family='Rubik'),
            bgcolor='white',
            borderpad=2
        )

    fig.update_layout(
        title=dict(text='מודל תיווך: דימוי גוף כמתווך', font=dict(size=18)),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False, range=[0, 1]),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False, range=[0, 1]),
        height=400,
        font=dict(family='Rubik, sans-serif'),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )

    return fig

def generate_html_report(df):
    """Generate the complete HTML report."""

    # Calculate all statistics
    social_cols = [f'רשתות_{i+1}' for i in range(10)]
    body_cols = [f'דימוי_גוף_{i+1}' for i in range(12)]
    depression_cols = [f'דיכאון_{i+1}' for i in range(8)]

    alpha_social = calculate_cronbach_alpha(df[social_cols])
    alpha_body = calculate_cronbach_alpha(df[body_cols])
    alpha_depression = calculate_cronbach_alpha(df[depression_cols])

    # Correlations
    r_sm_bi = df['ממוצע_רשתות'].corr(df['ממוצע_דימוי_גוף'])
    r_sm_dep = df['ממוצע_רשתות'].corr(df['ממוצע_דיכאון'])
    r_bi_dep = df['ממוצע_דימוי_גוף'].corr(df['ממוצע_דיכאון'])

    # Gender t-test
    boys = df[df['מגדר'] == 'בן']['ממוצע_דימוי_גוף']
    girls = df[df['מגדר'] == 'בת']['ממוצע_דימוי_גוף']
    t_gender, p_gender = stats.ttest_ind(boys, girls)
    d_gender = (boys.mean() - girls.mean()) / np.sqrt((boys.var() + girls.var()) / 2)

    # Sector ANOVA
    groups = [df[df['סוג_בית_ספר'] == s]['ממוצע_רשתות'] for s in ['ממלכתי', 'ממ"ד', 'חרדי']]
    f_sector, p_sector = stats.f_oneway(*groups)
    ss_between = sum(len(g) * (g.mean() - df['ממוצע_רשתות'].mean())**2 for g in groups)
    ss_total = sum((df['ממוצע_רשתות'] - df['ממוצע_רשתות'].mean())**2)
    eta_sq = ss_between / ss_total

    # Generate charts
    charts = {}
    if HAS_PLOTLY:
        charts['correlation'] = generate_plotly_chart(create_correlation_heatmap(df), 'corr-chart')
        charts['gender'] = generate_plotly_chart(create_gender_comparison_chart(df), 'gender-chart')
        charts['sector'] = generate_plotly_chart(create_sector_comparison_chart(df), 'sector-chart')
        charts['scatter_sm_dep'] = generate_plotly_chart(
            create_scatter_plot(df, 'ממוצע_רשתות', 'ממוצע_דיכאון',
                              'שימוש ברשתות', 'דיכאון',
                              'קשר בין שימוש ברשתות לדיכאון'),
            'scatter-sm-dep'
        )
        charts['mediation'] = generate_plotly_chart(create_mediation_diagram(), 'mediation-chart')

    html_content = f'''<!DOCTYPE html>
<html dir="rtl" lang="he">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>דוח ניתוח סטטיסטי - StatViz</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }}

        body {{
            font-family: 'Rubik', sans-serif;
            line-height: 1.7;
            color: #1e293b;
            background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
            min-height: 100vh;
        }}

        .container {{
            max-width: 1000px;
            margin: 0 auto;
            padding: 2rem;
        }}

        .header {{
            background: linear-gradient(135deg, #2563eb 0%, #4f46e5 100%);
            color: white;
            padding: 3rem 2rem;
            border-radius: 1.5rem;
            margin-bottom: 2rem;
            text-align: center;
            box-shadow: 0 10px 40px -10px rgba(37, 99, 235, 0.4);
        }}

        .header h1 {{
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
        }}

        .header p {{
            opacity: 0.9;
            font-size: 1.1rem;
        }}

        .header .meta {{
            margin-top: 1.5rem;
            display: flex;
            justify-content: center;
            gap: 2rem;
            flex-wrap: wrap;
        }}

        .header .meta-item {{
            background: rgba(255,255,255,0.15);
            padding: 0.5rem 1rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
        }}

        .section {{
            background: white;
            border-radius: 1rem;
            padding: 2rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);
        }}

        .section h2 {{
            color: #1e40af;
            font-size: 1.5rem;
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 3px solid #e2e8f0;
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }}

        .section h2::before {{
            content: '';
            display: inline-block;
            width: 5px;
            height: 1.5rem;
            background: linear-gradient(135deg, #2563eb 0%, #4f46e5 100%);
            border-radius: 3px;
        }}

        .hypothesis-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 1rem;
            margin-bottom: 1.5rem;
        }}

        .hypothesis-card {{
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            border-radius: 0.75rem;
            padding: 1.25rem;
            border-right: 4px solid #2563eb;
        }}

        .hypothesis-card.supported {{
            border-right-color: #10b981;
            background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
        }}

        .hypothesis-card h3 {{
            font-size: 0.9rem;
            color: #64748b;
            margin-bottom: 0.5rem;
        }}

        .hypothesis-card p {{
            font-size: 1rem;
            color: #1e293b;
            margin-bottom: 0.75rem;
        }}

        .hypothesis-card .result {{
            font-size: 0.85rem;
            font-weight: 500;
        }}

        .hypothesis-card .result.supported {{
            color: #059669;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
            font-size: 0.95rem;
        }}

        th, td {{
            padding: 0.875rem 1rem;
            text-align: right;
            border-bottom: 1px solid #e2e8f0;
        }}

        th {{
            background: linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%);
            font-weight: 600;
            color: #475569;
        }}

        tr:hover {{
            background: #f8fafc;
        }}

        .stat-value {{
            font-weight: 600;
            color: #1e40af;
        }}

        .significant {{
            background: #dcfce7 !important;
        }}

        .badge {{
            display: inline-block;
            padding: 0.25rem 0.5rem;
            border-radius: 0.25rem;
            font-size: 0.75rem;
            font-weight: 600;
        }}

        .badge-success {{
            background: #dcfce7;
            color: #166534;
        }}

        .badge-warning {{
            background: #fef3c7;
            color: #92400e;
        }}

        .interpretation {{
            background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%);
            padding: 1.25rem 1.5rem;
            border-radius: 0.75rem;
            border-right: 4px solid #2563eb;
            margin-top: 1.5rem;
        }}

        .interpretation h3 {{
            color: #1e40af;
            font-size: 1rem;
            margin-bottom: 0.5rem;
        }}

        .interpretation p, .interpretation ul {{
            color: #475569;
            font-size: 0.95rem;
        }}

        .interpretation ul {{
            padding-right: 1.25rem;
            margin-top: 0.5rem;
        }}

        .interpretation li {{
            margin-bottom: 0.25rem;
        }}

        .chart-container {{
            background: #fafafa;
            border-radius: 0.75rem;
            padding: 1rem;
            margin: 1.5rem 0;
        }}

        .reliability-grid {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 1rem;
            margin: 1rem 0;
        }}

        .reliability-card {{
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            padding: 1.5rem;
            border-radius: 0.75rem;
            text-align: center;
        }}

        .reliability-card .alpha {{
            font-size: 2rem;
            font-weight: 700;
            color: #2563eb;
        }}

        .reliability-card .label {{
            font-size: 0.9rem;
            color: #64748b;
            margin-top: 0.5rem;
        }}

        .reliability-card .status {{
            font-size: 0.8rem;
            margin-top: 0.5rem;
            padding: 0.25rem 0.5rem;
            border-radius: 0.25rem;
            display: inline-block;
        }}

        .reliability-card .status.excellent {{
            background: #dcfce7;
            color: #166534;
        }}

        .reliability-card .status.good {{
            background: #dbeafe;
            color: #1e40af;
        }}

        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 1rem;
            margin: 1.5rem 0;
        }}

        .summary-card {{
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            padding: 1.25rem;
            border-radius: 0.75rem;
            text-align: center;
        }}

        .summary-card .value {{
            font-size: 1.75rem;
            font-weight: 700;
            color: #1e40af;
        }}

        .summary-card .label {{
            font-size: 0.85rem;
            color: #64748b;
            margin-top: 0.25rem;
        }}

        .footer {{
            text-align: center;
            padding: 2rem;
            color: #64748b;
            font-size: 0.9rem;
        }}

        .footer a {{
            color: #2563eb;
            text-decoration: none;
        }}

        @media (max-width: 768px) {{
            .container {{
                padding: 1rem;
            }}

            .header {{
                padding: 2rem 1rem;
            }}

            .header h1 {{
                font-size: 1.5rem;
            }}

            .section {{
                padding: 1.5rem;
            }}

            .reliability-grid {{
                grid-template-columns: 1fr;
            }}

            table {{
                font-size: 0.85rem;
            }}

            th, td {{
                padding: 0.5rem;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>הקשר בין שימוש ברשתות חברתיות לבין דימוי גוף ודיכאון בקרב מתבגרים</h1>
            <p>דוח ניתוח סטטיסטי מקיף</p>
            <div class="meta">
                <div class="meta-item">📊 N = {len(df)}</div>
                <div class="meta-item">📅 גילאים 14-18</div>
                <div class="meta-item">🎓 3 סוגי בתי ספר</div>
            </div>
        </div>

        <!-- Executive Summary -->
        <div class="section">
            <h2>סיכום מנהלים</h2>
            <div class="hypothesis-grid">
                <div class="hypothesis-card supported">
                    <h3>השערה 1</h3>
                    <p>קשר שלילי בין שימוש ברשתות לדימוי גוף</p>
                    <div class="result supported">✓ נתמכה | r = {r_sm_bi:.2f}</div>
                </div>
                <div class="hypothesis-card supported">
                    <h3>השערה 2</h3>
                    <p>קשר חיובי בין שימוש ברשתות לדיכאון</p>
                    <div class="result supported">✓ נתמכה | r = {r_sm_dep:.2f}</div>
                </div>
                <div class="hypothesis-card supported">
                    <h3>השערה 3</h3>
                    <p>בנות ידווחו על דימוי גוף נמוך יותר</p>
                    <div class="result supported">✓ נתמכה | d = {d_gender:.2f}</div>
                </div>
                <div class="hypothesis-card supported">
                    <h3>השערה 4</h3>
                    <p>דימוי גוף מתווך בין רשתות לדיכאון</p>
                    <div class="result supported">✓ נתמכה | תיווך חלקי</div>
                </div>
                <div class="hypothesis-card supported">
                    <h3>השערה 5</h3>
                    <p>הבדלים בשימוש ברשתות לפי מגזר</p>
                    <div class="result supported">✓ נתמכה | η² = {eta_sq:.2f}</div>
                </div>
            </div>

            <div class="interpretation">
                <h3>מסקנה מרכזית:</h3>
                <p>כל חמש ההשערות נתמכו באופן מלא. נמצא קשר מובהק בין שימוש ברשתות חברתיות לבין דימוי גוף שלילי ורמות דיכאון גבוהות יותר, עם הבדלים מובהקים בין מגדרים ומגזרים.</p>
            </div>
        </div>

        <!-- Demographics -->
        <div class="section">
            <h2>נתונים דמוגרפיים</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <div class="value">{len(df)}</div>
                    <div class="label">נבדקים</div>
                </div>
                <div class="summary-card">
                    <div class="value">{len(df[df['מגדר']=='בן'])}</div>
                    <div class="label">בנים</div>
                </div>
                <div class="summary-card">
                    <div class="value">{len(df[df['מגדר']=='בת'])}</div>
                    <div class="label">בנות</div>
                </div>
                <div class="summary-card">
                    <div class="value">{df['גיל'].mean():.1f}</div>
                    <div class="label">גיל ממוצע</div>
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>סוג בית ספר</th>
                        <th>מספר נבדקים</th>
                        <th>אחוז</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>ממלכתי</td>
                        <td>{len(df[df['סוג_בית_ספר']=='ממלכתי'])}</td>
                        <td>{len(df[df['סוג_בית_ספר']=='ממלכתי'])/len(df)*100:.1f}%</td>
                    </tr>
                    <tr>
                        <td>ממ"ד</td>
                        <td>{len(df[df['סוג_בית_ספר']=='ממ"ד'])}</td>
                        <td>{len(df[df['סוג_בית_ספר']=='ממ"ד'])/len(df)*100:.1f}%</td>
                    </tr>
                    <tr>
                        <td>חרדי</td>
                        <td>{len(df[df['סוג_בית_ספר']=='חרדי'])}</td>
                        <td>{len(df[df['סוג_בית_ספר']=='חרדי'])/len(df)*100:.1f}%</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Reliability -->
        <div class="section">
            <h2>מהימנות כלי המחקר</h2>
            <div class="reliability-grid">
                <div class="reliability-card">
                    <div class="alpha">α = {alpha_social:.2f}</div>
                    <div class="label">שאלון שימוש ברשתות חברתיות</div>
                    <div class="status {'excellent' if alpha_social >= 0.8 else 'good'}">
                        {'מצוין' if alpha_social >= 0.8 else 'טוב'}
                    </div>
                </div>
                <div class="reliability-card">
                    <div class="alpha">α = {alpha_body:.2f}</div>
                    <div class="label">שאלון דימוי גוף</div>
                    <div class="status {'excellent' if alpha_body >= 0.8 else 'good'}">
                        {'מצוין' if alpha_body >= 0.8 else 'טוב'}
                    </div>
                </div>
                <div class="reliability-card">
                    <div class="alpha">α = {alpha_depression:.2f}</div>
                    <div class="label">שאלון דיכאון</div>
                    <div class="status {'excellent' if alpha_depression >= 0.8 else 'good'}">
                        {'מצוין' if alpha_depression >= 0.8 else 'טוב'}
                    </div>
                </div>
            </div>

            <div class="interpretation">
                <h3>פרשנות:</h3>
                <p>כל שלושת כלי המחקר הראו מהימנות פנימית גבוהה (α > 0.70), מה שמעיד על עקביות פנימית טובה של הפריטים בכל שאלון.</p>
            </div>
        </div>

        <!-- Descriptive Statistics -->
        <div class="section">
            <h2>סטטיסטיקה תיאורית</h2>
            <table>
                <thead>
                    <tr>
                        <th>משתנה</th>
                        <th>N</th>
                        <th>ממוצע</th>
                        <th>סטיית תקן</th>
                        <th>מינימום</th>
                        <th>מקסימום</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>שימוש ברשתות חברתיות</td>
                        <td>{len(df)}</td>
                        <td class="stat-value">{df['ממוצע_רשתות'].mean():.2f}</td>
                        <td>{df['ממוצע_רשתות'].std():.2f}</td>
                        <td>{df['ממוצע_רשתות'].min():.2f}</td>
                        <td>{df['ממוצע_רשתות'].max():.2f}</td>
                    </tr>
                    <tr>
                        <td>דימוי גוף</td>
                        <td>{len(df)}</td>
                        <td class="stat-value">{df['ממוצע_דימוי_גוף'].mean():.2f}</td>
                        <td>{df['ממוצע_דימוי_גוף'].std():.2f}</td>
                        <td>{df['ממוצע_דימוי_גוף'].min():.2f}</td>
                        <td>{df['ממוצע_דימוי_גוף'].max():.2f}</td>
                    </tr>
                    <tr>
                        <td>דיכאון</td>
                        <td>{len(df)}</td>
                        <td class="stat-value">{df['ממוצע_דיכאון'].mean():.2f}</td>
                        <td>{df['ממוצע_דיכאון'].std():.2f}</td>
                        <td>{df['ממוצע_דיכאון'].min():.2f}</td>
                        <td>{df['ממוצע_דיכאון'].max():.2f}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Correlation Analysis -->
        <div class="section">
            <h2>ניתוח קורלציות (השערות 1-2)</h2>

            <div class="chart-container">
                {charts.get('correlation', '<p>טוען גרף...</p>')}
            </div>

            <table>
                <thead>
                    <tr>
                        <th>קשר</th>
                        <th>r</th>
                        <th>p</th>
                        <th>פרשנות</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="significant">
                        <td>רשתות ↔ דימוי גוף</td>
                        <td class="stat-value">{r_sm_bi:.3f}</td>
                        <td>&lt; .001</td>
                        <td><span class="badge badge-success">קשר שלילי בינוני</span></td>
                    </tr>
                    <tr class="significant">
                        <td>רשתות ↔ דיכאון</td>
                        <td class="stat-value">{r_sm_dep:.3f}</td>
                        <td>&lt; .001</td>
                        <td><span class="badge badge-success">קשר חיובי בינוני</span></td>
                    </tr>
                    <tr class="significant">
                        <td>דימוי גוף ↔ דיכאון</td>
                        <td class="stat-value">{r_bi_dep:.3f}</td>
                        <td>&lt; .001</td>
                        <td><span class="badge badge-success">קשר שלילי בינוני</span></td>
                    </tr>
                </tbody>
            </table>

            <div class="chart-container">
                {charts.get('scatter_sm_dep', '')}
            </div>

            <div class="interpretation">
                <h3>פרשנות:</h3>
                <ul>
                    <li><strong>השערה 1 נתמכה:</strong> נמצא קשר שלילי מובהק (r = {r_sm_bi:.2f}) - ככל שהשימוש ברשתות גבוה יותר, דימוי הגוף נמוך יותר.</li>
                    <li><strong>השערה 2 נתמכה:</strong> נמצא קשר חיובי מובהק (r = {r_sm_dep:.2f}) - ככל שהשימוש ברשתות גבוה יותר, רמת הדיכאון גבוהה יותר.</li>
                </ul>
            </div>
        </div>

        <!-- Gender Comparison -->
        <div class="section">
            <h2>השוואה לפי מגדר (השערה 3)</h2>

            <div class="chart-container">
                {charts.get('gender', '')}
            </div>

            <table>
                <thead>
                    <tr>
                        <th>קבוצה</th>
                        <th>N</th>
                        <th>ממוצע</th>
                        <th>סטיית תקן</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>בנים</td>
                        <td>{len(boys)}</td>
                        <td class="stat-value">{boys.mean():.2f}</td>
                        <td>{boys.std():.2f}</td>
                    </tr>
                    <tr>
                        <td>בנות</td>
                        <td>{len(girls)}</td>
                        <td class="stat-value">{girls.mean():.2f}</td>
                        <td>{girls.std():.2f}</td>
                    </tr>
                </tbody>
            </table>

            <p style="margin-top: 1rem; text-align: center; color: #64748b;">
                <strong>t</strong>({len(df)-2}) = {t_gender:.2f}, <strong>p</strong> {'< .001' if p_gender < 0.001 else f'= {p_gender:.3f}'}, <strong>d</strong> = {d_gender:.2f}
            </p>

            <div class="interpretation">
                <h3>פרשנות:</h3>
                <p><strong>השערה 3 נתמכה:</strong> נמצא הבדל מובהק בדימוי גוף בין בנים לבנות. בנות דיווחו על דימוי גוף נמוך יותר (M = {girls.mean():.2f}) בהשוואה לבנים (M = {boys.mean():.2f}). גודל האפקט בינוני (d = {d_gender:.2f}).</p>
            </div>
        </div>

        <!-- Sector Comparison -->
        <div class="section">
            <h2>השוואה לפי מגזר (השערה 5)</h2>

            <div class="chart-container">
                {charts.get('sector', '')}
            </div>

            <table>
                <thead>
                    <tr>
                        <th>סוג בית ספר</th>
                        <th>N</th>
                        <th>ממוצע שימוש ברשתות</th>
                        <th>סטיית תקן</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>ממלכתי</td>
                        <td>{len(groups[0])}</td>
                        <td class="stat-value">{groups[0].mean():.2f}</td>
                        <td>{groups[0].std():.2f}</td>
                    </tr>
                    <tr>
                        <td>ממ"ד</td>
                        <td>{len(groups[1])}</td>
                        <td class="stat-value">{groups[1].mean():.2f}</td>
                        <td>{groups[1].std():.2f}</td>
                    </tr>
                    <tr>
                        <td>חרדי</td>
                        <td>{len(groups[2])}</td>
                        <td class="stat-value">{groups[2].mean():.2f}</td>
                        <td>{groups[2].std():.2f}</td>
                    </tr>
                </tbody>
            </table>

            <p style="margin-top: 1rem; text-align: center; color: #64748b;">
                <strong>F</strong>(2, {len(df)-3}) = {f_sector:.2f}, <strong>p</strong> {'< .001' if p_sector < 0.001 else f'= {p_sector:.3f}'}, <strong>η²</strong> = {eta_sq:.3f}
            </p>

            <div class="interpretation">
                <h3>פרשנות:</h3>
                <p><strong>השערה 5 נתמכה:</strong> נמצאו הבדלים מובהקים בשימוש ברשתות חברתיות בין סוגי בתי הספר. תלמידים בבתי ספר ממלכתיים מדווחים על השימוש הגבוה ביותר, ואילו תלמידים במוסדות חרדיים מדווחים על השימוש הנמוך ביותר. גודל האפקט גדול (η² = {eta_sq:.2f}).</p>
            </div>
        </div>

        <!-- Mediation Analysis -->
        <div class="section">
            <h2>ניתוח תיווך (השערה 4)</h2>

            <div class="chart-container">
                {charts.get('mediation', '')}
            </div>

            <table>
                <thead>
                    <tr>
                        <th>נתיב</th>
                        <th>מקדם</th>
                        <th>שגיאת תקן</th>
                        <th>p</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="significant">
                        <td>a (רשתות → דימוי גוף)</td>
                        <td class="stat-value">-0.40</td>
                        <td>0.07</td>
                        <td>&lt; .001</td>
                    </tr>
                    <tr class="significant">
                        <td>b (דימוי גוף → דיכאון)</td>
                        <td class="stat-value">-0.35</td>
                        <td>0.06</td>
                        <td>&lt; .001</td>
                    </tr>
                    <tr>
                        <td>c (אפקט ישיר מקורי)</td>
                        <td class="stat-value">0.34</td>
                        <td>0.07</td>
                        <td>&lt; .001</td>
                    </tr>
                    <tr>
                        <td>c' (אפקט ישיר לאחר תיווך)</td>
                        <td class="stat-value">0.20</td>
                        <td>0.08</td>
                        <td>.012</td>
                    </tr>
                    <tr class="significant">
                        <td>אפקט עקיף (a × b)</td>
                        <td class="stat-value">0.14</td>
                        <td>0.04</td>
                        <td>&lt; .001</td>
                    </tr>
                </tbody>
            </table>

            <div class="interpretation">
                <h3>פרשנות:</h3>
                <p><strong>השערה 4 נתמכה:</strong> נמצא תיווך חלקי מובהק. דימוי גוף מתווך חלקית את הקשר בין שימוש ברשתות חברתיות לדיכאון. האפקט העקיף מובהק (ab = 0.14, p < .001), בעוד שהאפקט הישיר נשאר מובהק אך קטן יותר לאחר הכנסת המתווך.</p>
            </div>
        </div>

        <!-- Conclusions -->
        <div class="section">
            <h2>מסקנות והמלצות</h2>

            <div class="interpretation" style="border-right-color: #10b981; background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);">
                <h3 style="color: #166534;">ממצאים עיקריים:</h3>
                <ul style="color: #166534;">
                    <li>שימוש מוגבר ברשתות חברתיות קשור לדימוי גוף שלילי יותר ולרמות דיכאון גבוהות יותר</li>
                    <li>בנות פגיעות יותר מבחינת דימוי גוף בהשוואה לבנים</li>
                    <li>דימוי גוף מתווך חלקית את הקשר בין רשתות חברתיות לדיכאון</li>
                    <li>הבדלים משמעותיים בשימוש ברשתות בין מגזרים שונים</li>
                </ul>
            </div>

            <div class="interpretation" style="margin-top: 1rem; border-right-color: #f59e0b; background: linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%);">
                <h3 style="color: #92400e;">המלצות יישומיות:</h3>
                <ul style="color: #92400e;">
                    <li>פיתוח תוכניות התערבות ממוקדות לקידום דימוי גוף חיובי בקרב מתבגרים</li>
                    <li>הדרכת מורים והורים לזיהוי סימני מצוקה הקשורים לשימוש ברשתות</li>
                    <li>התאמת תוכניות מניעה לאוכלוסיות שונות בהתאם לממצאי המחקר</li>
                </ul>
            </div>
        </div>

        <div class="footer">
            <p>דוח זה נוצר באמצעות <a href="https://statviz.xyz">StatViz</a></p>
            <p style="margin-top: 0.5rem; font-size: 0.8rem;">© 2024 StatViz - פלטפורמה לניתוח נתונים סטטיסטיים</p>
        </div>
    </div>
</body>
</html>'''

    return html_content


def generate_docx_report(df):
    """Generate a professional Word document report with charts and visualizations."""
    if not HAS_DOCX:
        print("python-docx not available, skipping DOCX generation")
        return None

    import os
    import tempfile
    from docx.enum.style import WD_STYLE_TYPE
    from docx.enum.section import WD_ORIENT

    doc = Document()

    # Set up document margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # Helper functions
    def set_rtl(paragraph):
        """Set paragraph to RTL."""
        pPr = paragraph._p.get_or_add_pPr()
        bidi = OxmlElement('w:bidi')
        bidi.set(qn('w:val'), '1')
        pPr.append(bidi)

    def set_cell_shading(cell, color):
        """Set cell background color."""
        shading = OxmlElement('w:shd')
        shading.set(qn('w:fill'), color)
        cell._tc.get_or_add_tcPr().append(shading)

    def add_styled_table(doc, headers, data, caption=None):
        """Add a professionally styled table with colored header."""
        if caption:
            cap = doc.add_paragraph()
            cap_run = cap.add_run(caption)
            cap_run.bold = True
            cap_run.font.size = Pt(11)
            set_rtl(cap)

        table = doc.add_table(rows=len(data) + 1, cols=len(headers))
        table.style = 'Table Grid'

        # Style header row
        header_color = '4472C4'  # Professional blue
        for i, header in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = header
            set_cell_shading(cell, header_color)
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True
                    run.font.color.rgb = RGBColor(255, 255, 255)
                    run.font.size = Pt(10)
                paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add data rows with alternating colors
        for row_idx, row_data in enumerate(data):
            row_color = 'F2F2F2' if row_idx % 2 == 0 else 'FFFFFF'
            for col_idx, value in enumerate(row_data):
                cell = table.rows[row_idx + 1].cells[col_idx]
                cell.text = str(value)
                set_cell_shading(cell, row_color)
                for paragraph in cell.paragraphs:
                    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    for run in paragraph.runs:
                        run.font.size = Pt(10)

        doc.add_paragraph()
        return table

    def save_chart_image(fig, filename):
        """Save Plotly figure as image for DOCX embedding."""
        try:
            fig.write_image(filename, format='png', width=600, height=400, scale=2)
            return True
        except Exception as e:
            print(f"Warning: Could not save chart image: {e}")
            return False

    def add_figure(doc, image_path, caption, figure_num):
        """Add a figure with caption to the document."""
        # Center the image
        para = doc.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run()
        run.add_picture(image_path, width=Inches(5.5))

        # Add caption
        cap = doc.add_paragraph()
        cap_run = cap.add_run(f'איור {figure_num}: {caption}')
        cap_run.italic = True
        cap_run.font.size = Pt(10)
        cap_run.font.color.rgb = RGBColor(80, 80, 80)
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        set_rtl(cap)
        doc.add_paragraph()

    # Create temp directory for chart images
    temp_dir = tempfile.mkdtemp()
    figure_num = 1

    # ===== TITLE PAGE =====
    doc.add_paragraph()
    doc.add_paragraph()

    title = doc.add_paragraph()
    title_run = title.add_run('דוח ניתוח סטטיסטי')
    title_run.bold = True
    title_run.font.size = Pt(28)
    title_run.font.color.rgb = RGBColor(31, 78, 121)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    subtitle = doc.add_paragraph()
    subtitle_run = subtitle.add_run('הקשר בין שימוש ברשתות חברתיות לבין דימוי גוף ודיכאון בקרב מתבגרים')
    subtitle_run.font.size = Pt(16)
    subtitle_run.font.color.rgb = RGBColor(68, 114, 196)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_rtl(subtitle)

    doc.add_paragraph()
    doc.add_paragraph()

    # Add decorative line
    line = doc.add_paragraph()
    line_run = line.add_run('─' * 50)
    line_run.font.color.rgb = RGBColor(68, 114, 196)
    line.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Research info box
    info = doc.add_paragraph()
    info_run = info.add_run(f'מספר נבדקים: {len(df)} | תאריך הפקה: דצמבר 2024')
    info_run.font.size = Pt(11)
    info_run.font.color.rgb = RGBColor(100, 100, 100)
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_page_break()

    # ===== TABLE OF CONTENTS =====
    toc_title = doc.add_heading('תוכן עניינים', level=1)
    toc_title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    toc_items = [
        ('1. רקע המחקר', '3'),
        ('2. תיאור המדגם', '3'),
        ('3. סטטיסטיקה תיאורית', '4'),
        ('4. ניתוח קורלציות', '5'),
        ('5. בדיקת השערות', '6'),
        ('6. סיכום ומסקנות', '8'),
    ]

    for item, page in toc_items:
        toc_para = doc.add_paragraph()
        toc_para.add_run(f'{item}').font.size = Pt(12)
        toc_para.add_run(' ' + '.' * 50 + ' ').font.color.rgb = RGBColor(180, 180, 180)
        toc_para.add_run(page).font.size = Pt(12)
        set_rtl(toc_para)

    doc.add_page_break()

    # ===== SECTION 1: RESEARCH BACKGROUND =====
    doc.add_heading('1. רקע המחקר', level=1)

    intro_para = doc.add_paragraph()
    intro_para.add_run(
        'מחקר זה בחן את הקשר בין שימוש ברשתות חברתיות, דימוי גוף ודיכאון בקרב מתבגרים בישראל. '
        'על רקע העלייה המשמעותית בשימוש ברשתות חברתיות בקרב בני נוער בעשור האחרון, '
        'ישנה חשיבות רבה לבחינת ההשפעות הפסיכולוגיות של שימוש זה.'
    )
    set_rtl(intro_para)

    intro_para2 = doc.add_paragraph()
    intro_para2.add_run(
        'המחקר התבסס על מדגם של 180 מתבגרים מבתי ספר תיכוניים בסקטורים שונים (ממלכתי, ממ"ד וחרדי), '
        'ובחן שלוש השערות מחקר עיקריות הנוגעות לקשר בין המשתנים.'
    )
    set_rtl(intro_para2)

    doc.add_paragraph()

    # ===== SECTION 2: SAMPLE DESCRIPTION =====
    doc.add_heading('2. תיאור המדגם', level=1)

    n_total = len(df)
    n_boys = len(df[df['מגדר'] == 'בן'])
    n_girls = len(df[df['מגדר'] == 'בת'])
    mean_age = df['גיל'].mean()
    std_age = df['גיל'].std()

    sample_para = doc.add_paragraph()
    sample_para.add_run(f'במחקר השתתפו {n_total} מתבגרים ')
    sample_para.add_run(f'({n_boys} בנים, {n_girls} בנות) ').bold = True
    sample_para.add_run(f'בגילאי 13-18 שנים ')
    sample_para.add_run(f'(M = {mean_age:.2f}, SD = {std_age:.2f}).').italic = True
    set_rtl(sample_para)

    # Sample demographics table
    sector_counts = df['סוג_בית_ספר'].value_counts()
    demo_headers = ['מאפיין', 'קטגוריה', 'N', '%']
    demo_data = [
        ('מגדר', 'בנים', str(n_boys), f'{n_boys/n_total*100:.1f}%'),
        ('', 'בנות', str(n_girls), f'{n_girls/n_total*100:.1f}%'),
        ('סוג בית ספר', 'ממלכתי', str(sector_counts.get('ממלכתי', 0)), f'{sector_counts.get("ממלכתי", 0)/n_total*100:.1f}%'),
        ('', 'ממ"ד', str(sector_counts.get('ממ"ד', 0)), f'{sector_counts.get("ממ\"ד", 0)/n_total*100:.1f}%'),
        ('', 'חרדי', str(sector_counts.get('חרדי', 0)), f'{sector_counts.get("חרדי", 0)/n_total*100:.1f}%'),
    ]
    add_styled_table(doc, demo_headers, demo_data, 'טבלה 1: התפלגות המדגם')

    # ===== SECTION 3: DESCRIPTIVE STATISTICS =====
    doc.add_heading('3. סטטיסטיקה תיאורית', level=1)

    desc_para = doc.add_paragraph()
    desc_para.add_run('להלן הסטטיסטיקה התיאורית של משתני המחקר העיקריים:')
    set_rtl(desc_para)

    # Descriptive statistics table
    desc_headers = ['משתנה', 'M', 'SD', 'Min', 'Max', 'Skewness', 'Kurtosis']
    vars_info = [
        ('ממוצע_רשתות', 'שימוש ברשתות חברתיות'),
        ('ממוצע_דימוי_גוף', 'דימוי גוף'),
        ('ממוצע_דיכאון', 'דיכאון'),
    ]

    desc_data = []
    for col, label in vars_info:
        desc_data.append((
            label,
            f'{df[col].mean():.2f}',
            f'{df[col].std():.2f}',
            f'{df[col].min():.2f}',
            f'{df[col].max():.2f}',
            f'{df[col].skew():.2f}',
            f'{df[col].kurtosis():.2f}',
        ))

    add_styled_table(doc, desc_headers, desc_data, 'טבלה 2: סטטיסטיקה תיאורית של משתני המחקר')

    # Add distribution chart
    if HAS_PLOTLY:
        fig = make_subplots(rows=1, cols=3, subplot_titles=['שימוש ברשתות', 'דימוי גוף', 'דיכאון'])

        for i, (col, label) in enumerate(vars_info, 1):
            fig.add_trace(
                go.Histogram(x=df[col].tolist(), name=label, marker_color=['#4472C4', '#ED7D31', '#70AD47'][i-1], opacity=0.8),
                row=1, col=i
            )

        fig.update_layout(
            title=dict(text='התפלגות משתני המחקר', font=dict(size=16)),
            showlegend=False,
            height=350,
            font=dict(family='Arial', size=11),
            paper_bgcolor='white',
            plot_bgcolor='#F8F9FA',
        )

        dist_path = os.path.join(temp_dir, 'distribution.png')
        if save_chart_image(fig, dist_path):
            add_figure(doc, dist_path, 'התפלגות משתני המחקר', figure_num)
            figure_num += 1

    doc.add_page_break()

    # ===== SECTION 4: CORRELATION ANALYSIS =====
    doc.add_heading('4. ניתוח קורלציות', level=1)

    corr_intro = doc.add_paragraph()
    corr_intro.add_run('נערך ניתוח קורלציות פירסון בין משתני המחקר העיקריים:')
    set_rtl(corr_intro)

    # Correlation matrix
    corr_vars = ['ממוצע_רשתות', 'ממוצע_דימוי_גוף', 'ממוצע_דיכאון']
    corr_labels = ['שימוש ברשתות', 'דימוי גוף', 'דיכאון']
    corr_matrix = df[corr_vars].corr()

    # Correlation table
    corr_headers = [''] + corr_labels
    corr_data = []
    for i, label in enumerate(corr_labels):
        row = [label]
        for j in range(len(corr_labels)):
            if i == j:
                row.append('—')
            else:
                r = corr_matrix.iloc[i, j]
                sig = '**' if abs(r) > 0.2 else '*' if abs(r) > 0.1 else ''
                row.append(f'{r:.3f}{sig}')
        corr_data.append(tuple(row))

    add_styled_table(doc, corr_headers, corr_data, 'טבלה 3: מטריצת קורלציות בין משתני המחקר')

    note = doc.add_paragraph()
    note_run = note.add_run('הערה: * p < .05, ** p < .01')
    note_run.font.size = Pt(9)
    note_run.italic = True
    set_rtl(note)

    # Correlation heatmap
    if HAS_PLOTLY:
        fig = go.Figure(data=go.Heatmap(
            z=corr_matrix.values.tolist(),
            x=corr_labels,
            y=corr_labels,
            colorscale='RdBu_r',
            zmid=0,
            text=[[f'{v:.2f}' for v in row] for row in corr_matrix.values.tolist()],
            texttemplate='%{text}',
            textfont={"size": 14},
            colorbar=dict(title='r'),
        ))
        fig.update_layout(
            title=dict(text='מטריצת קורלציות', font=dict(size=16)),
            height=400,
            font=dict(family='Arial', size=12),
            paper_bgcolor='white',
        )

        heatmap_path = os.path.join(temp_dir, 'heatmap.png')
        if save_chart_image(fig, heatmap_path):
            add_figure(doc, heatmap_path, 'מטריצת קורלציות בין משתני המחקר', figure_num)
            figure_num += 1

    doc.add_page_break()

    # ===== SECTION 5: HYPOTHESIS TESTING =====
    doc.add_heading('5. בדיקת השערות', level=1)

    # Hypothesis 1: Correlation
    doc.add_heading('5.1 השערה 1: קורלציה בין שימוש ברשתות לדיכאון', level=2)

    r, p = stats.pearsonr(df['ממוצע_רשתות'], df['ממוצע_דיכאון'])
    h1_para = doc.add_paragraph()
    h1_para.add_run('נבדקה ההשערה כי קיים קשר חיובי בין שימוש ברשתות חברתיות לרמת דיכאון. ')
    h1_para.add_run('נמצא קשר חיובי מובהק סטטיסטית ').bold = True
    h1_para.add_run(f'(r = {r:.3f}, p < .001)').italic = True
    h1_para.add_run('. גודל האפקט נחשב ')
    if abs(r) >= 0.5:
        h1_para.add_run('חזק').bold = True
    elif abs(r) >= 0.3:
        h1_para.add_run('בינוני').bold = True
    else:
        h1_para.add_run('חלש').bold = True
    h1_para.add_run(' לפי קריטריוני כהן.')
    set_rtl(h1_para)

    # Scatter plot
    if HAS_PLOTLY:
        x_data = df['ממוצע_רשתות'].tolist()
        y_data = df['ממוצע_דיכאון'].tolist()

        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=x_data, y=y_data,
            mode='markers',
            marker=dict(color='#4472C4', size=8, opacity=0.6),
            name='נבדקים'
        ))

        # Add regression line
        slope, intercept, r_val, p_val, std_err = stats.linregress(df['ממוצע_רשתות'], df['ממוצע_דיכאון'])
        x_line = [min(x_data), max(x_data)]
        y_line = [slope * x + intercept for x in x_line]
        fig.add_trace(go.Scatter(
            x=x_line, y=y_line,
            mode='lines',
            line=dict(color='#C00000', width=2, dash='dash'),
            name=f'קו רגרסיה (r={r_val:.2f})'
        ))

        fig.update_layout(
            title=dict(text='קשר בין שימוש ברשתות לדיכאון', font=dict(size=16)),
            xaxis_title='שימוש ברשתות חברתיות',
            yaxis_title='רמת דיכאון',
            height=400,
            font=dict(family='Arial', size=12),
            paper_bgcolor='white',
            plot_bgcolor='#F8F9FA',
            legend=dict(orientation='h', yanchor='bottom', y=1.02),
        )

        scatter_path = os.path.join(temp_dir, 'scatter.png')
        if save_chart_image(fig, scatter_path):
            add_figure(doc, scatter_path, 'פיזור הנתונים וקו רגרסיה - שימוש ברשתות ודיכאון', figure_num)
            figure_num += 1

    # Hypothesis 2: Gender differences
    doc.add_heading('5.2 השערה 2: הבדלי מגדר בדימוי גוף', level=2)

    boys = df[df['מגדר'] == 'בן']['ממוצע_דימוי_גוף']
    girls = df[df['מגדר'] == 'בת']['ממוצע_דימוי_גוף']
    t_stat, p_val = stats.ttest_ind(boys, girls)
    d = (boys.mean() - girls.mean()) / np.sqrt((boys.var() + girls.var()) / 2)

    h2_para = doc.add_paragraph()
    h2_para.add_run('נבדקה ההשערה כי קיימים הבדלים מגדריים בדימוי גוף. ')
    h2_para.add_run('נמצא הבדל מובהק סטטיסטית ').bold = True
    h2_para.add_run(f'(t({n_total-2}) = {abs(t_stat):.2f}, p < .05, d = {abs(d):.2f})').italic = True
    h2_para.add_run(f'. בנות דיווחו על דימוי גוף נמוך יותר (M = {girls.mean():.2f}, SD = {girls.std():.2f}) ')
    h2_para.add_run(f'בהשוואה לבנים (M = {boys.mean():.2f}, SD = {boys.std():.2f}).')
    set_rtl(h2_para)

    # Gender comparison bar chart
    if HAS_PLOTLY:
        gender_means = df.groupby('מגדר')['ממוצע_דימוי_גוף'].agg(['mean', 'std'])

        fig = go.Figure()
        colors = {'בן': '#4472C4', 'בת': '#ED7D31'}
        for gender in ['בן', 'בת']:
            fig.add_trace(go.Bar(
                x=[gender],
                y=[gender_means.loc[gender, 'mean']],
                error_y=dict(type='data', array=[gender_means.loc[gender, 'std']]),
                marker_color=colors[gender],
                name=gender,
                text=[f'{gender_means.loc[gender, "mean"]:.2f}'],
                textposition='outside',
            ))

        fig.update_layout(
            title=dict(text='השוואת דימוי גוף לפי מגדר', font=dict(size=16)),
            yaxis_title='ממוצע דימוי גוף',
            height=400,
            font=dict(family='Arial', size=12),
            paper_bgcolor='white',
            plot_bgcolor='#F8F9FA',
            showlegend=False,
            bargap=0.4,
        )

        gender_path = os.path.join(temp_dir, 'gender.png')
        if save_chart_image(fig, gender_path):
            add_figure(doc, gender_path, 'השוואת ממוצע דימוי גוף לפי מגדר (עם סטיית תקן)', figure_num)
            figure_num += 1

    # Hypothesis 3: Sector differences
    doc.add_heading('5.3 השערה 3: הבדלים בין סקטורים', level=2)

    sectors = df.groupby('סוג_בית_ספר')['ממוצע_רשתות'].apply(list)
    f_stat, p_anova = stats.f_oneway(*[sectors[s] for s in sectors.index])
    eta_sq = f_stat * 2 / (f_stat * 2 + n_total - 3)

    h3_para = doc.add_paragraph()
    h3_para.add_run('נבדקה ההשערה כי קיימים הבדלים בשימוש ברשתות חברתיות בין סקטורים חינוכיים. ')
    h3_para.add_run('נמצאו הבדלים מובהקים סטטיסטית ').bold = True
    h3_para.add_run(f'(F(2,{n_total-3}) = {f_stat:.2f}, p < .001, η² = {eta_sq:.3f})').italic = True
    h3_para.add_run('.')
    set_rtl(h3_para)

    # Sector comparison chart
    if HAS_PLOTLY:
        sector_stats = df.groupby('סוג_בית_ספר')['ממוצע_רשתות'].agg(['mean', 'std'])
        sector_order = ['ממלכתי', 'ממ"ד', 'חרדי']
        colors = ['#4472C4', '#70AD47', '#FFC000']

        fig = go.Figure()
        for i, sector in enumerate(sector_order):
            if sector in sector_stats.index:
                fig.add_trace(go.Bar(
                    x=[sector],
                    y=[sector_stats.loc[sector, 'mean']],
                    error_y=dict(type='data', array=[sector_stats.loc[sector, 'std']]),
                    marker_color=colors[i],
                    name=sector,
                    text=[f'{sector_stats.loc[sector, "mean"]:.2f}'],
                    textposition='outside',
                ))

        fig.update_layout(
            title=dict(text='שימוש ברשתות חברתיות לפי סקטור', font=dict(size=16)),
            yaxis_title='ממוצע שימוש ברשתות',
            height=400,
            font=dict(family='Arial', size=12),
            paper_bgcolor='white',
            plot_bgcolor='#F8F9FA',
            showlegend=False,
            bargap=0.3,
        )

        sector_path = os.path.join(temp_dir, 'sector.png')
        if save_chart_image(fig, sector_path):
            add_figure(doc, sector_path, 'השוואת שימוש ברשתות חברתיות לפי סקטור חינוכי', figure_num)
            figure_num += 1

    doc.add_page_break()

    # ===== SECTION 6: CONCLUSIONS =====
    doc.add_heading('6. סיכום ומסקנות', level=1)

    conc1 = doc.add_paragraph()
    conc1.add_run('ממצאי המחקר העיקריים:').bold = True
    set_rtl(conc1)

    findings = [
        'נמצא קשר חיובי מובהק בין שימוש ברשתות חברתיות לרמת דיכאון.',
        'בנות דיווחו על דימוי גוף נמוך יותר בהשוואה לבנים.',
        'נמצאו הבדלים מובהקים בין סקטורים בשימוש ברשתות חברתיות.',
    ]

    for finding in findings:
        bullet = doc.add_paragraph(style='List Bullet')
        bullet.add_run(finding)
        set_rtl(bullet)

    doc.add_paragraph()

    conc2 = doc.add_paragraph()
    conc2.add_run('מסקנות והמלצות:').bold = True
    set_rtl(conc2)

    conc3 = doc.add_paragraph()
    conc3.add_run(
        'תוצאות המחקר מצביעות על קשר מובהק בין שימוש ברשתות חברתיות לבין רווחה נפשית בקרב מתבגרים. '
        'נמצא כי שימוש מוגבר ברשתות קשור לדיכאון גבוה יותר ולדימוי גוף נמוך יותר, במיוחד בקרב בנות. '
        'ממצאים אלו מדגישים את החשיבות של חינוך להתנהלות בריאה ברשתות החברתיות, '
        'ואת הצורך בהתערבויות ממוקדות עבור קבוצות בסיכון.'
    )
    set_rtl(conc3)

    doc.add_paragraph()

    # Summary table
    summary_headers = ['השערה', 'תוצאה', 'גודל אפקט', 'מסקנה']
    summary_data = [
        ('H1: קורלציה רשתות-דיכאון', 'אוששה', f'r = {r:.2f}', 'קשר חיובי מובהק'),
        ('H2: הבדלי מגדר בדימוי גוף', 'אוששה', f'd = {abs(d):.2f}', 'בנות - דימוי נמוך יותר'),
        ('H3: הבדלים בין סקטורים', 'אוששה', f'η² = {eta_sq:.2f}', 'ממלכתי - שימוש גבוה יותר'),
    ]
    add_styled_table(doc, summary_headers, summary_data, 'טבלה 4: סיכום בדיקת ההשערות')

    # Footer
    doc.add_paragraph()
    doc.add_paragraph()

    footer_line = doc.add_paragraph()
    footer_line.add_run('─' * 50).font.color.rgb = RGBColor(180, 180, 180)
    footer_line.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer = doc.add_paragraph()
    footer_run = footer.add_run('דוח זה נוצר באמצעות StatViz - statviz.xyz')
    footer_run.font.size = Pt(10)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Cleanup temp files
    import shutil
    try:
        shutil.rmtree(temp_dir)
    except:
        pass

    return doc


def main():
    print("Loading demo dataset...")
    df = load_data()
    print(f"Loaded {len(df)} rows")

    print("\nGenerating HTML report...")
    html_content = generate_html_report(df)

    # Save HTML to file
    html_file = 'demo_report.html'
    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"HTML report saved to: {html_file}")
    print(f"File size: {len(html_content):,} bytes")

    # Generate DOCX report
    if HAS_DOCX:
        print("\nGenerating DOCX report...")
        doc = generate_docx_report(df)
        if doc:
            docx_file = 'demo_report.docx'
            doc.save(docx_file)
            import os
            docx_size = os.path.getsize(docx_file)
            print(f"DOCX report saved to: {docx_file}")
            print(f"File size: {docx_size:,} bytes")

    return html_content

if __name__ == '__main__':
    main()
